CREATE VIEW `company_comparison_view` AS
SELECT 
    company,
    year,
    reportDate,
    segment,
    subsegment,
    -- Financial Numbers (in thousands) - exact field names as expected by HTML
    `Net Revenue`,
    `Cost of Goods`,
    `Gross Margin`, 
    `SGA`,
    `Operating Profit`,
    `Net Profit`,
    `Inventory`,
    `Total Assets`,
    -- Financial Indicators - exact field names as expected by HTML
    `Cost of Goods %`,
    `Gross Margin %`,
    `SGA %`,
    `Operating Profit Margin %`,
    `Net Profit Margin %`,
    `Inventory Turnover`,
    `Current Ratio`,
    `Quick Ratio`,
    `Debt to Equity`,
    `Asset Turnover`,
    `Return on Assets`,
    `Three Year Revenue CAGR`
FROM `benchmarks 2024 view`;

-- Create views for all years (2018-2024) that the HTML page expects
CREATE VIEW `company_comparison_2024_view` AS
SELECT 
    company,
    year,
    reportDate,
    segment,
    subsegment,
    `Net Revenue`,
    `Cost of Goods`,
    `Gross Margin`, 
    `SGA`,
    `Operating Profit`,
    `Net Profit`,
    `Inventory`,
    `Total Assets`,
    `Cost of Goods %`,
    `Gross Margin %`,
    `SGA %`,
    `Operating Profit Margin %`,
    `Net Profit Margin %`,
    `Inventory Turnover`,
    `Current Ratio`,
    `Quick Ratio`,
    `Debt to Equity`,
    `Asset Turnover`,
    `Return on Assets`,
    `Three Year Revenue CAGR`
FROM `benchmarks 2024 view`;

CREATE VIEW `company_comparison_2023_view` AS
SELECT 
    company,
    year,
    reportDate,
    segment,
    subsegment,
    `Net Revenue`,
    `Cost of Goods`,
    `Gross Margin`, 
    `SGA`,
    `Operating Profit`,
    `Net Profit`,
    `Inventory`,
    `Total Assets`,
    `Cost of Goods %`,
    `Gross Margin %`,
    `SGA %`,
    `Operating Profit Margin %`,
    `Net Profit Margin %`,
    `Inventory Turnover`,
    `Current Ratio`,
    `Quick Ratio`,
    `Debt to Equity`,
    `Asset Turnover`,
    `Return on Assets`,
    `Three Year Revenue CAGR`
FROM `benchmarks 2023 view`;

CREATE VIEW `company_comparison_2022_view` AS
SELECT 
    company,
    year,
    reportDate,
    segment,
    subsegment,
    `Net Revenue`,
    `Cost of Goods`,
    `Gross Margin`, 
    `SGA`,
    `Operating Profit`,
    `Net Profit`,
    `Inventory`,
    `Total Assets`,
    `Cost of Goods %`,
    `Gross Margin %`,
    `SGA %`,
    `Operating Profit Margin %`,
    `Net Profit Margin %`,
    `Inventory Turnover`,
    `Current Ratio`,
    `Quick Ratio`,
    `Debt to Equity`,
    `Asset Turnover`,
    `Return on Assets`,
    `Three Year Revenue CAGR`
FROM `benchmarks 2022 view`;

CREATE VIEW `company_comparison_2021_view` AS
SELECT 
    company,
    year,
    reportDate,
    segment,
    subsegment,
    `Net Revenue`,
    `Cost of Goods`,
    `Gross Margin`, 
    `SGA`,
    `Operating Profit`,
    `Net Profit`,
    `Inventory`,
    `Total Assets`,
    `Cost of Goods %`,
    `Gross Margin %`,
    `SGA %`,
    `Operating Profit Margin %`,
    `Net Profit Margin %`,
    `Inventory Turnover`,
    `Current Ratio`,
    `Quick Ratio`,
    `Debt to Equity`,
    `Asset Turnover`,
    `Return on Assets`,
    `Three Year Revenue CAGR`
FROM `benchmarks 2021 view`;

CREATE VIEW `company_comparison_2020_view` AS
SELECT 
    company,
    year,
    reportDate,
    segment,
    subsegment,
    `Net Revenue`,
    `Cost of Goods`,
    `Gross Margin`, 
    `SGA`,
    `Operating Profit`,
    `Net Profit`,
    `Inventory`,
    `Total Assets`,
    `Cost of Goods %`,
    `Gross Margin %`,
    `SGA %`,
    `Operating Profit Margin %`,
    `Net Profit Margin %`,
    `Inventory Turnover`,
    `Current Ratio`,
    `Quick Ratio`,
    `Debt to Equity`,
    `Asset Turnover`,
    `Return on Assets`,
    `Three Year Revenue CAGR`
FROM `benchmarks 2020 view`;

CREATE VIEW `company_comparison_2019_view` AS
SELECT 
    company,
    year,
    reportDate,
    segment,
    subsegment,
    `Net Revenue`,
    `Cost of Goods`,
    `Gross Margin`, 
    `SGA`,
    `Operating Profit`,
    `Net Profit`,
    `Inventory`,
    `Total Assets`,
    `Cost of Goods %`,
    `Gross Margin %`,
    `SGA %`,
    `Operating Profit Margin %`,
    `Net Profit Margin %`,
    `Inventory Turnover`,
    `Current Ratio`,
    `Quick Ratio`,
    `Debt to Equity`,
    `Asset Turnover`,
    `Return on Assets`,
    `Three Year Revenue CAGR`
FROM `benchmarks 2019 view`;

CREATE VIEW `company_comparison_2018_view` AS
SELECT 
    company,
    year,
    reportDate,
    segment,
    subsegment,
    `Net Revenue`,
    `Cost of Goods`,
    `Gross Margin`, 
    `SGA`,
    `Operating Profit`,
    `Net Profit`,
    `Inventory`,
    `Total Assets`,
    `Cost of Goods %`,
    `Gross Margin %`,
    `SGA %`,
    `Operating Profit Margin %`,
    `Net Profit Margin %`,
    `Inventory Turnover`,
    `Current Ratio`,
    `Quick Ratio`,
    `Debt to Equity`,
    `Asset Turnover`,
    `Return on Assets`,
    `Three Year Revenue CAGR`
FROM `benchmarks 2018 view`;

